function [fx_erp,fy_erp,fz_erp] = force_erp(mjd,rsat,vsat,r_sun)
% ----------------------------------------------------------------------
% Purpose:
% Acceleration due to the earth radiation pressure. 
% This model is only for GNSS satellites, not for LEO satellites which needs
% more precise model, such as a numerical one.
% ----------------------------------------------------------------------
% Input arguments:
% - mjd          : time variable
% - rsat         : satellite position vector (m)
% - vsat         : satellite velocity vector
% - r_sun        : Sun position vector
% 
% Output arguments:
% - fx,fy,fz:	 : Accelerations in the inertial frame (m/s^2)
% ----------------------------------------------------------------------
  global SVNID
  %! Force generated by repro3 routines
  % -----------------------------------
  ERM = 1;
  ANT = 0;
  GRD = 1;
  REFF = 0; 
  YSAT(1:3) = rsat;
  YSAT(4:6) = vsat;
  R_SUN = r_sun;
  KAPPA = 0.d0;
  MONTH = 1;
  MJD = mjd;
  
  %print*,'Block type, SVNID, BLKID,  power, MASS = ', BLKTYP, SVNID, BLKID,power, MASS
  ACCEL = ERPFBOXW(ERM,ANT,GRD,REFF,YSAT,R_SUN,KAPPA,MONTH,SVNID,MJD);
  
  fx_erp = ACCEL(1);
  fy_erp = ACCEL(2);
  fz_erp = ACCEL(3);
end